### ISSUE TITLE
V9 is putting the jobs on pending state

### ISSUE THREAD

**Issue by snajeebz** [OCA/connector-interfaces#34]
Hi,
Tried importing two different files one with 96 records and second with 1200 records, but the status of the both jobs has been pending since 3-4 hours, Records are validated. can you

**Comment by slayer49** [comment]
Did you ever get this working?  I am experience the same issue.   Also, how can you delete a job?

**Comment by snajeebz** [comment]
I wrote a program on python, to read from the source and write it to the odoo server using rest api. It was a better alternative to the auto importer.
