### ISSUE TITLE
v8 base_import_async: Concurrent import of models with parent-columns leads to broken data

### ISSUE THREAD

**Issue by tremlin** [OCA/connector-interfaces#35]
I observed the following problem in a v8 installation with `base_import_async`.

When I uploaded a CSV file for the model `stock.quant.package` with a few thousand packages (see [stock.quant.package.csv.txt](https://github.com/OCA/connector-interfaces/files/603292/stock.quant.package.csv.txt)) and checked the "Import in the background" box, the `parent_left`/`parent_right` data was garbage. In a normal situation the following SQL statement should return 0.
```sql
select count(*) 
from stock_quant_package p1, 
stock_quant_package p2
where p1.id < p2.id 
and p1.parent_left = p2.parent_left
and p1.parent_right = p2.parent_right
```
However, after the import I had a few thousand distinct packages with the same parent_left/parent_right information, which clearly is wrong.

I don't think that this is a problem of the module itself, I suppose this is a bug in Odoo that is exposed by concurrency. I am not sure what the best way is to deal with this. The first idea that I had was to call `_parent_store_compute` at the end of every import chunk, but this might lead to concurrency issues (DB serialization failures) among the jobs which are tedious to resolve.

I think the best solution would be to show an error message when the asynchronous import is used for a model with 'parent' columns since this causes problems regardless of whether the data to be imported contains parent information: If it contains parent information, there will probably be database serialization failures. If it does not contain parent information, the parent_left/_right data structure will be garbage.

**Comment by florian-dacosta** [comment]
I guess it is too late, but I saw this now...
I guess your problem is the same described here : https://github.com/odoo/odoo/issues/14493

An easy solution would be to configure the channel used for import with only one worker. This way, Odoo won't create 2 packages at the same time and you should not have this problem.
Else, you can apply a patch to remove parent_left/right from packages, like it has been done for version 10.
