### ISSUE TITLE
connector-importer missing import.type views?

### ISSUE THREAD

**Issue by GSLabIt** [OCA/connector-interfaces#48]
Hi there,

are views missing? alternatively how is possible to define an `import.type`?

Thx

**Comment by simahawk** [comment]
Main reason is: they are strictly tied to the components you register.
Unlikely you want to keep component and configuration out of sync.
Hence, usually they come from configuration in your module. Like:
```xml

  <record id="import_references" model="import.type">
    <field name="name">References</field>
    <field name="key">references</field>
    <field name="settings">
whatever.reference.model::mymodule.reference.importer
whatever.related.model::mymodule.related.importer
    </field>
  </record>
```
Maybe we can add some readonly views but you can already access their details by clicking on the import type field on the recordset.
Feel free to propose a PR if you think it could be useful ;)

**Comment by GSLabIt** [comment]
@simahawk well .. probably I misunderstood how that works :grimacing: Is there any ref to totorial and/or examples?

**Comment by simahawk** [comment]
sorry, no docs for now as I did not have enough time to  write them.
But the code [is commented](https://github.com/OCA/connector-interfaces/blob/11.0/connector_importer/models/import_type.py#L11) and [tested](https://github.com/OCA/connector-interfaces/tree/11.0/connector_importer/tests).
I know it's not that much if you don't know how connector works.
Probably we'll have to work on the module for v12.
I'll see if we can create an example package.

**Comment by edisuc** [comment]
An example package would be great. Maybe a simple CSV with two to three columns and a few records of data.
