### ISSUE TITLE
As a user i can't create a report

### ISSUE THREAD

**Issue by elvise** [OCA/connector-interfaces#92]
Hi @simahawk ping you directly because i as i can see you are the maintainer of this module: connector_importer_product

I'm testing in runboat but there is something weird, please check this video: [Link](https://recordit.co/irmVN09gcB)

**Comment by simahawk** [comment]
@elvise sorry I missed this. Which version are you using? I'm pretty sure is fixed in v15 the migration is pending here #94

**Comment by elvise** [comment]
> @elvise sorry I missed this. Which version are you using? I'm pretty sure is fixed in v15 the migration is pending here #94 

@simahawk Thanks for your answer. We are in V14

**Comment by simahawk** [comment]
@elvise this shouldbe fixed, let me know pls
